import Head from "next/head";

const Header = () => {
  return (
        <Head>
        <title>Vymo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/vymo.svg" />
      </Head>
  )
}

export default Header