import Head from "next/head";
import Navbar from "../components/Navbar";
import HeroSection from "../components/HeroSection";
import Goals from "../components/Goals";
import Products from "../components/Products";
import Solutions from "../components/Solutions";
import Company from "../components/Company";
import Resources from "../components/Resources";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Vymo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/vymo.svg" />
      </Head>
      <Navbar />
      <HeroSection />
      <Goals />
      <Products />
      <Solutions />
      <Company />
      <Resources />
  
     
  
    </div>
  );
}
