import Head from "next/head";
import Navbar from "../components/Navbar";
import HeroSection from "../components/HeroSection";
import Goals from "../components/Goals";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Vymo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/vymo.svg" />
      </Head>
      <Navbar />
      <HeroSection />
      <Goals />
  
    </div>
  );
}
